#!/bin/sh

# theme config
source $ZDIR/powerlevel10k

# save more history
HISTFILE=$HOME/.zsh_history
HISTSIZE=10000
SAVEHIST=10000

# linux style ls colors
export LSCOLORS=ExGxBxDxCxEgEdxbxgxcxd

# autosuggest settings
ZSH_AUTOSUGGEST_STRATEGY=(history completion)
#unset ZSH_AUTOSUGGEST_USE_ASYNC
